// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB429IBic5h7Bd_es_hQ8x0E_bIBfNPGM',
    appId: '1:685047787574:web:5c50546db64da687ce2897',
    messagingSenderId: '685047787574',
    projectId: 'study-app-flutter-7655c',
    authDomain: 'study-app-flutter-7655c.firebaseapp.com',
    storageBucket: 'study-app-flutter-7655c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEGrPrcxru8bwCWwDbvpgi2SZy85AOYfQ',
    appId: '1:685047787574:android:6741c81726cb9fd0ce2897',
    messagingSenderId: '685047787574',
    projectId: 'study-app-flutter-7655c',
    storageBucket: 'study-app-flutter-7655c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYnuz9FP2weKlGk8n_1XnIXlL9ojg21n4',
    appId: '1:558363260763:ios:5c2e0a6d87c4104ba28c7e',
    messagingSenderId: '558363260763',
    projectId: 'virtual-career-d298e',
    storageBucket: 'virtual-career-d298e.firebasestorage.app',
    iosBundleId: 'com.example.virtualCareer',
  );
}